### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by alagos** [bung87/vscode-gemfile#1]
I simply hover on a gem definition, but is not displaying any info.
Not sure what info I can show to help debug this, these are my [VSCode settings](https://gist.github.com/alagos/a2ae1c10ea14a9895bbdb17a6eca7718). 
Using VScode:
```
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```

**Comment by bung87** [comment]
as of version 0.4.0 fixed
