### ISSUE TITLE
What is the license of this extension?

### ISSUE THREAD

**Issue by jankeromnes** [bung87/vscode-gemfile#3]
Hello @bung87!

We would like to publish your very useful "vscode-rails" and "vscode-gemfile" VS Code extensions to the open-source vendor-neutral registry [Open VSX](https://open-vsx.org) which will allow them to be installed in [Theia](theia-ide.org/), [Gitpod](https://www.gitpod.io), [VSCodium](https://github.com/VSCodium/vscodium), and other non-Microsoft developer tools.

So we've added "vscode-rails" to Open VSX's auto-publishing script in https://github.com/open-vsx/publish-extensions/commit/97989a5c679e474915de8dedc19c04e19c53e8e5 However, publishing currently fails because of `Error: Cannot resolve dependency: bung87.vscode-gemfile`.

So we would like to also publish "vscode-gemfile". However, there is no explicit license in this repository, while Open VSX currently only supports extensions with open-source licenses like MIT, Apache 2.0, ISC, etc.

Could you please add a license to https://github.com/bung87/vscode-gemfile ? 🙏

**Comment by bung87** [comment]
sure thing, it will be MIT, let me add it.

**Comment by jankeromnes** [comment]
Perfect, many thanks for the quick reply! 💯
