### ISSUE TITLE
Add to OpenVSX registry

### ISSUE THREAD

**Issue by taylorthurlow** [bung87/vscode-gemfile#4]
Hi, I'm unable to install the vscode-rails extension in the Onivim2 editor because this extension is a dependency but is not present on the OpenVSX registry. It would be great if it were to be added!

**Comment by bung87** [comment]
How to do that, I remember they ask me add license file to my vscode-rails project, then that project included.

**Comment by taylorthurlow** [comment]
This project, already being on MIT, I don't think you'll need to make any changes to the repo. The license will need to be set in the package.json as well I think. Your OpenVSX registry account is the only one that has permission to send extensions to the `bung87` repository. You should be able to download `ovsx` on NPM, and then send it with `npx ovsx publish --pat YOUR_VSX_REGISTRY_TOKEN` from your main project directory.

Further instructions here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension

**Comment by bung87** [comment]
https://github.com/EclipseFdn/open-vsx.org/issues/491 wait for this

**Comment by bung87** [comment]
After granted permission , I re run workflow action , it says it's already published , I checked the https://open-vsx.org/extension/bung87/vscode-gemfile, it shows "Published 11 months ago", Can you confirm if there's problem?

**Comment by taylorthurlow** [comment]
Sorry, it looks like there is not a problem on your side. Must be some problem with the editor I'm using not properly fetching the dependencies of the Rails vscode extension. Sorry to waste your time.
